"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { ShoppingBag,ShoppingCart } from "lucide-react";
import type { Book } from "@/lib/catalog";
import { amazonUrl,rakutenUrl } from "@/lib/catalog";
import { BookCover } from "./BookCover";
import { weightedDiscovery } from "@/lib/discovery";
function Stores({book}:{book:Book}){const shared="inline-flex min-h-11 min-w-0 items-center justify-center gap-1 rounded-2xl border border-black bg-white px-2 text-[11px] font-extrabold shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2";return <div className="grid grid-cols-2 gap-2"><a href={amazonUrl(book)} target="_blank" rel="sponsored noopener noreferrer" className={`${shared} text-[#146eb4] hover:bg-[#f2f8fc] focus-visible:ring-[#146eb4]`}><ShoppingCart size={13}/><span>Amazon</span></a><a href={rakutenUrl(book)} target="_blank" rel="sponsored noopener noreferrer" className={`${shared} text-[#bf0000] hover:bg-[#fff4f4] focus-visible:ring-[#bf0000]`}><ShoppingBag size={13}/><span>楽天</span></a></div>}
export function BookCard({book,rank,priority=false,hideActions=false,showMeta=false}:{book:Book;rank?:number;priority?:boolean;hideActions?:boolean;showMeta?:boolean}){return <article className="group min-w-0"><Link href={`/books/${book.id}`} aria-label={`${book.title}の詳細を見る`} className="block rounded-md outline-none focus-visible:ring-2 focus-visible:ring-[#b4232f] focus-visible:ring-offset-4 focus-visible:ring-offset-white"><div className="relative origin-center transition duration-300 ease-out group-hover:z-10 group-hover:scale-[1.06] group-hover:drop-shadow-[0_18px_24px_rgba(0,0,0,.28)]">{rank?<span className="absolute -left-2 -top-2 z-10 grid h-9 min-w-9 place-items-center rounded-full bg-[#b4232f] px-2 text-lg font-black text-white shadow-xl">{rank}</span>:null}<BookCover book={book} priority={priority}/><span className="absolute inset-x-2 bottom-2 translate-y-1 rounded-lg bg-black/80 py-2 text-center text-[11px] font-bold text-white opacity-0 backdrop-blur transition group-hover:translate-y-0 group-hover:opacity-100">詳細を見る</span></div>{showMeta?<><h3 className="mt-3 line-clamp-2 min-h-10 text-[13px] font-bold leading-5 text-[#171717]">{book.title}</h3><p className="mt-1 line-clamp-1 text-xs text-[#777]">{book.author}</p></>:null}</Link>{hideActions?null:<div className="mt-3"><Stores book={book}/></div>}</article>}
export function BookGrid({books,ranked=false}:{books:Book[];ranked?:boolean}){return <div className="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7">{books.map((book,index)=><BookCard key={book.id} book={book} rank={ranked?index+1:undefined}/>)}</div>}
const popularityOf=(book:Book,index:number)=>book.amazonRank||book.rakutenRank?Math.max(.35,1-Math.min(book.amazonRank??book.rakutenRank??50,50)/60):(book.featured ? .9 : book.awards?.length ? .82 : book.classicGroup ? .72 : Math.max(.4,.68-index*.006));
export function BookRail({books,ranked=false,priority=false,discoveryKey,limit=12}:{books:Book[];ranked?:boolean;priority?:boolean;discoveryKey?:string;limit?:number}){const [visible,setVisible]=useState(()=>discoveryKey?books.slice(0,limit):books);const applied=useRef(false);useEffect(()=>{if(!discoveryKey||applied.current)return;applied.current=true;setVisible(weightedDiscovery(books,{key:book=>`${discoveryKey}:${book.isbn}`,popularity:popularityOf,limit}))},[books,discoveryKey,limit]);return <div className="book-rail -mx-4 flex snap-x snap-mandatory gap-3 overflow-x-auto scroll-smooth px-4 pb-8 pt-3 sm:gap-4 md:-mx-8 md:px-8">{visible.map((book,index)=><div key={book.isbn} className="w-[36vw] min-w-[132px] max-w-[168px] shrink-0 snap-start md:w-[158px]"><BookCard book={book} rank={ranked?index+1:undefined} priority={priority&&index<5}/></div>)}</div>}