import Link from "next/link";
import { notFound } from "next/navigation";
import { BookCover } from "@/components/books/BookCover";
import { BookRail } from "@/components/books/BookCard";
import { Breadcrumbs } from "@/components/site/Breadcrumbs";
import { PurchaseButtons } from "@/components/books/PurchaseButtons";
import { bookRecord, relatedWorkShelf } from "@/lib/catalog-repository";
import { coverUrl, publisherName, amazonUrl, rakutenUrl } from "@/lib/catalog";
import { breadcrumbJson,createMetadata,SITE_URL } from "@/lib/seo";

export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params;const title=decodeURIComponent(id).replace(/-\d{6}$/u,"");return createMetadata(title,"本の詳細","/books/"+id)}
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const book=await bookRecord(id);if(!book)notFound();const related=book.databaseId?await relatedWorkShelf(book.databaseId,8):[];const crumbs=breadcrumbJson([{name:"ホーム",url:"/"},{name:book.title,url:`/books/${book.id}`}]);const product={"@context":"https://schema.org","@type":"Book",name:book.title,author:{"@type":"Person",name:book.author},isbn:book.isbn,image:coverUrl(book),description:book.synopsis,url:`${SITE_URL}/books/${book.id}`,publisher:{"@type":"Organization",name:publisherName(book)},sameAs:[amazonUrl(book),rakutenUrl(book)]};return <div className="netflix-page"><div className="mx-auto max-w-[1280px] px-4 md:px-8"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([crumbs,product])}}/><Breadcrumbs items={[{label:book.title}]}/><section className="grid gap-9 py-10 md:grid-cols-[280px_1fr] md:gap-16 md:py-16 lg:grid-cols-[340px_1fr]"><div className="mx-auto w-full max-w-[300px]"><BookCover book={book} priority sizes="(max-width:768px) 76vw,340px"/></div><div className="flex flex-col justify-center"><h1 className="font-serif text-[clamp(2.4rem,6vw,5rem)] font-semibold leading-[1.08] tracking-[-.05em] text-white">{book.title}</h1><Link href={`/authors/${book.authorSlug}`} className="mt-4 text-lg text-white/60 hover:text-white">{book.author}</Link><dl className="mt-8 grid gap-5 border-y border-white/10 py-6"><div><dt className="text-xs font-bold tracking-widest text-white/35">あらすじ</dt><dd className="mt-3 max-w-2xl text-sm leading-7 text-white/70 md:text-base md:leading-8">{book.synopsis}</dd></div><div><dt className="text-xs font-bold tracking-widest text-white/35">出版社</dt><dd className="mt-2 text-sm text-white/75">{publisherName(book)}</dd></div>{book.isbn?<div><dt className="text-xs font-bold tracking-widest text-white/35">ISBN</dt><dd className="mt-2 text-sm text-white/75">{book.isbn}</dd></div>:null}{book.awards?.length?<div><dt className="text-xs font-bold tracking-widest text-white/35">受賞歴</dt><dd className="mt-2 flex flex-wrap gap-2">{book.awards.map(award=><span key={award.name+award.year} className="rounded-full bg-[#e50914]/15 px-3 py-1.5 text-xs font-bold text-[#ff868c]">{award.year}年 {award.name}</span>)}</dd></div>:null}</dl><div className="mt-7 max-w-xl"><PurchaseButtons book={book}/></div></div></section><section className="netflix-section pb-20"><h2 className="rail-title">この本を選んだあなたへ</h2><BookRail books={related} discoveryKey={`related:${book.isbn}`} limit={8}/></section></div></div>}